### ISSUE TITLE
Add custom tracking calls to library

### ISSUE THREAD

**Issue by sumassemblyreqd** [wdunn001/ng-gainsight#1]
I used this library in an application that I'm developing and it worked, so great job!

I would like the ability to do custom event tracking to the library so that we can issue the calls to aptrinsic in our Angular services, like a 
"this.gainsight.track(CustomEvent)" or something like that, where CustomEvent is a bit open to what properties that we can put in it.

Do you think this would be possible?

**Comment by wdunn001** [comment]
hey brother ya gimme a sec

**Comment by wdunn001** [comment]
No I don't believe this is supported by them. You have to setup the events in there GUI. I just wrote this cause I had a project that used them and there integration was awful.
